version: "3.8"
services:
     app_express:
        container_name: express_app
        build: .
        ports:
          - "5000:5000"
        env_file:
          - .env  
        depends_on:
         - mongo
     mongo:
       image: mongo:4.4
       restart: always
       environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=example
       ports:
        - "27017:27017"
       volumes:
        - mongo_data:/data/db
         
volumes: 
  mongo_data: